### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by WofWca** [incubated-geek-cc/video-to-GIF#2]
Hey, thanks for sharing this software!
However, nobody can modify and improve it due to the lack of a license. Would you consider adding one? I would recommend GPL-v3-or-later or Apache-2.0. If you're open to this, I can make an MR.

**Comment by incubated-geek-cc** [comment]
@WofWca Hi there! Many thanks for heads-up. Have added GPL-v3 license to the application.

**Comment by WofWca** [comment]
Thank you!
